# -*- coding: utf-8 -*-
"""Nonlinear_Dynamics_Analysis_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptC-f9qKAGt-E5aS3Qb9KdGIHKFdp4b0
"""

import numpy as np
import plotly.graph_objects as go
from scipy.signal import argrelextrema
from scipy.io import loadmat # Import loadmat for .mat files
from scipy.spatial import KDTree
import matplotlib.pyplot as plt

def get_time_delay(time_series, max_delay=100):
    """
    Estimates the optimal time delay (tau) by finding the first local minimum
    of the autocorrelation function.
    """
    # Calculate the autocorrelation of the sequence
    mean_ts = np.mean(time_series)
    acf = np.correlate(time_series - mean_ts, time_series - mean_ts, mode='full')

    # Take the second half of the ACF and normalize it
    acf = acf[len(acf)//2:] / acf[len(acf)//2]

    # Find the first local minimum
    local_mins = argrelextrema(acf[:max_delay], np.less)[0]

    if len(local_mins) > 0:
        return local_mins[0]
    else:
        return 1 # Fallback if no minimum is found within max_delay

def reconstruct_phase_space(time_series, tau, m):
    """
    Reconstructs the phase space using Takens' Delay Embedding Theorem.

    Parameters:
    - time_series: 1D array of the data
    - tau: Time delay integer
    - m: Embedding dimension integer
    """
    N = len(time_series)
    if N - (m - 1) * tau <= 0:
        raise ValueError("Time series is too short for this embedding dimension and delay.")

    # Create the embedded vectors
    embedded_vectors = []
    for i in range(N - (m - 1) * tau):
        # Create a point: [x(t), x(t + tau), x(t + 2*tau), ... x(t + (m-1)*tau)]
        point = [time_series[i + j * tau] for j in range(m)]
        embedded_vectors.append(point)

    return np.array(embedded_vectors)

def calculate_largest_lyapunov_exponent(phase_space, tau, m, delta_t=1, max_divergence_steps=100):
    """
    Calculates the largest Lyapunov exponent using Rosenstein's algorithm.

    Parameters:
    - phase_space: Reconstructed phase space array (N, m)
    - tau: Time delay
    - m: Embedding dimension
    - delta_t: Time step between consecutive data points (default: 1)
    - max_divergence_steps: Maximum number of steps to track divergence

    Returns:
    - largest_lyapunov_exponent: Estimated largest Lyapunov exponent
    - plot_time_steps: Array of time steps for plotting
    - plot_avg_log_divergences: Array of average log divergences for plotting
    """
    N_points = phase_space.shape[0]
    # Use a KD-tree for efficient nearest neighbor search.
    tree = KDTree(phase_space)

    # Stores the log divergence for each reference point over time.
    all_log_divergences = np.full((N_points, max_divergence_steps), np.nan)

    for i in range(N_points):
        # Find the nearest neighbor (excluding itself).
        distances, indices = tree.query(phase_space[i], k=2)
        nearest_neighbor_idx = indices[1]
        initial_distance = distances[1]

        if initial_distance == 0:
            continue

        for k in range(max_divergence_steps):
            if i + k < N_points and nearest_neighbor_idx + k < N_points:
                current_divergence_distance = np.linalg.norm(phase_space[i + k] - phase_space[nearest_neighbor_idx + k])
                if current_divergence_distance > 0:
                    all_log_divergences[i, k] = np.log(current_divergence_distance)

    # Calculate the average log divergence over all reference points.
    avg_log_divergences = np.nanmean(all_log_divergences, axis=0)

    valid_indices_for_fit = ~np.isnan(avg_log_divergences)

    if np.sum(valid_indices_for_fit) < 2:
        return np.nan, np.array([]), np.array([])

    time_steps_for_fit = np.arange(len(avg_log_divergences))[valid_indices_for_fit]
    log_divergence_values_for_fit = avg_log_divergences[valid_indices_for_fit]

    # Perform linear regression to find the slope (Lyapunov exponent).
    try:
        slope, intercept = np.polyfit(time_steps_for_fit * delta_t, log_divergence_values_for_fit, 1)
    except np.linalg.LinAlgError:
        slope = np.nan

    return slope, time_steps_for_fit, log_divergence_values_for_fit


# ==========================================
# Execution and Visualization
# ==========================================

np.random.seed(70)

# --- User Defined Parameters ---
user_defined_m = 2      # Set your desired embedding dimension (e.g., 2 for 2D, 3 for 3D)
user_defined_tau = 12   # Set your desired time delay, or None to calculate automatically
# --------------------------------

# --- Code to load time series from a .mat file ---
try:
    mat_data = loadmat('/content/INDIA_SM_1948_2014.mat')

    grid_data = mat_data['GRID']

    # Extract grid IDs from the 3rd row (index 2)
    grid_ids = grid_data[2, :]

    # --- User Input: Specify the desired grid ID here ---
    # For example, if you want the time series for grid ID 77.5, set desired_grid_id = 77.5
    desired_grid_id = 28695 # <--- PLEASE SET YOUR DESIRED GRID ID HERE
    # -----------------------------------------------------

    if desired_grid_id is None:
        raise ValueError("Please set 'desired_grid_id' to the grid ID you want to analyze.")

    # Find the column index corresponding to the desired_grid_id
    if desired_grid_id in grid_ids:
        column_index = np.where(grid_ids == desired_grid_id)[0][0]
        # Extract the time series data from the 4th row (index 3) onwards for the selected column
        soil_moisture = grid_data[3:, column_index]
    else:
        raise ValueError(f"Grid ID {desired_grid_id} not found in the .mat file.")
except FileNotFoundError:
    raise FileNotFoundError("The file 'INDIA_SM_1948_2014.mat' was not found. Please ensure it is in the correct directory.")
except ValueError as e:
    raise ValueError(f"Error processing .mat file or desired_grid_id: {e}")

t = np.linspace(0, 50, len(soil_moisture)) # Adjust t based on loaded data length

# 2. Calculate the optimal time delay (tau)
if user_defined_tau is None:
    tau = get_time_delay(soil_moisture, max_delay=min(50, len(soil_moisture) // 4)) # Adjust max_delay for potentially shorter series
else:
    tau = user_defined_tau

# 3. Reconstruct the Phase Space
m = user_defined_m # Use user-defined embedding dimension
phase_space = reconstruct_phase_space(soil_moisture, tau, m)

# 4. Generate the Interactive Plot based on embedding dimension

if m == 2:
    fig = go.Figure(data=[go.Scatter(
        x=phase_space[:, 0],
        y=phase_space[:, 1],
        mode='lines',
        line=dict(
            color='black', # Set color to black
            width=2
        )
    )])
    fig.update_layout(
        title="2D Phase Space Reconstruction (Takens' Embedding)",
        xaxis_title="x(t)",
        yaxis_title=f"x(t + {tau})",
        margin=dict(l=0, r=0, b=0, t=40)
    )
elif m == 3:
    fig = go.Figure(data=[go.Scatter3d(
        x=phase_space[:, 0],
        y=phase_space[:, 1],
        z=phase_space[:, 2],
        mode='lines',
        line=dict(
            color='black', # Set color to black
            width=2
        )
    )])
    fig.update_layout(
        title="3D Phase Space Reconstruction (Takens' Embedding)",
        scene=dict(
            xaxis_title="x(t)",
            yaxis_title=f"x(t + {tau})",
            zaxis_title=f"x(t + {2*tau})"
        ),
        margin=dict(l=0, r=0, b=0, t=40)
    )
else:
    fig = go.Figure(data=[go.Scatter(
        x=phase_space[:, 0],
        y=phase_space[:, 1],
        mode='lines',
        line=dict(
            color='black', # Set color to black
            width=2
        )
    )])
    fig.update_layout(
        title=f"Phase Space Reconstruction (m={m}, showing 2D projection)",
        xaxis_title="x(t)",
        yaxis_title=f"x(t + {tau})",
        margin=dict(l=0, r=0, b=0, t=40)
    )

print(f"Grid ID: {desired_grid_id}")
print(f"Embedding Dimension (m): {m}")
print(f"Time Delay (tau): {tau}")

# Opens the interactive graph in your default web browser
fig.show()

# --- Calculate and print the Lyapunov exponent ---
largest_lyapunov_exponent, plot_time_steps, plot_avg_log_divergences = calculate_largest_lyapunov_exponent(phase_space, tau, m)
print(f"Estimated Largest Lyapunov Exponent: {largest_lyapunov_exponent:.4f}")

# --- Plot the log divergence graph ---
if plot_time_steps.size > 0 and plot_avg_log_divergences.size > 0:
    plt.figure(figsize=(10, 6))
    plt.plot(plot_time_steps, plot_avg_log_divergences, 'o-', label='Average Log Divergence')

    # Optionally, plot the linear fit if it was successful
    if not np.isnan(largest_lyapunov_exponent):
        # Recalculate slope and intercept from the valid points for plotting the line
        valid_indices = ~np.isnan(plot_avg_log_divergences)
        time_steps_for_fit = np.arange(len(plot_avg_log_divergences))[valid_indices]
        log_divergence_values_for_fit = plot_avg_log_divergences[valid_indices]

        if len(time_steps_for_fit) > 1:
            slope_plot, intercept_plot = np.polyfit(time_steps_for_fit, log_divergence_values_for_fit, 1)
            plt.plot(time_steps_for_fit, slope_plot * time_steps_for_fit + intercept_plot, 'r--', label=f'Linear Fit (Slope={slope_plot:.4f})')

    plt.xlabel("Time Steps (k)")
    plt.ylabel("Average Log Divergence")
    plt.title("Log Divergence Plot for Lyapunov Exponent Calculation")
    plt.grid(True)
    plt.legend()
    plt.show()

